### ISSUE TITLE
"SysEquiv" test broke

### ISSUE THREAD

**Issue by KingaS03** [ilifau/assStackQuestion#87] opened 2020-09-09 14:20 UTC
"SysEquiv" fails to work when testing the correctness of an answer. 

We have observed this on problems, which were implemented earlier. They were also tested and everything has worked properly. And now tests of type "SysEquiv" do produce some error, namely:

"The answer test failed to execute correctly: please alert your teacher. CAS failed to return any data. result:StackReturn(ATSysEquiv(STACKSA,STACKTA))

Incorrect answer. Try again!
TEST_FAILED"

**Comment by sangwinc** [comment] 2020-09-09 14:39
Ok, this looks like the CAS timed out.  Can you send me the two inputs which threw this error and I'll look in more detail?

**Comment by sangwinc** [comment] 2020-09-09 16:25
Thanks for emailing me the question off the list.  The "SysEquiv" test uses the Grobner basis, which is expensive to calculate and likely to lead to a timeout on the CAS.  You could ask your admin to up the timeout a little.

However, in this case you are expecting a single equation, so I think "SysEquiv" is not the test you want to use. I think AlgEquiv would be better here anyway.  Was there a reason you needed "SysEquiv"?

Your question works on my STACK "development" machine (an old, under-powered PC) so this is not a bug in STACK!  I recommend you close this issue.

**Closed** 2020-09-10 09:40 UTC
